name: homelab-media


services:

  # VPN
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun
    
    ports:
      - 8080:8080

    environment:
      TZ: ${TZ}
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: ${VPN_TYPE}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}

    volumes:
      - ${HOMELAB_ROOT}/appdata/gluetun:/gluetun

    networks:
      - vpn
      - media

  # Downloaders
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    network_mode: "service:gluetun"

    depends_on:
      - gluetun

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080

    volumes:
      - ${HOMELAB_ROOT}/appdata/qbittorrent:/config
      - ${HOMELAB_ROOT}/data:/data

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    
    ports:
      - "8081:8080"
    
    networks:
      - media
      - monitoring

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      
    volumes:
      - sabnzbd-config:/config
      - ${HOMELAB_ROOT}/data:/data

  # Automation
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}

    volumes:
      - ${HOMELAB_ROOT}/appdata/prowlarr:/config

    ports:
      - "9696:9696"

    networks:
      - media
      - monitoring

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOMELAB_ROOT}/appdata/sonarr:/config
      - ${HOMELAB_ROOT}/data:/data

    ports:
      - "8989:8989"

    networks:
      - media
      - monitoring

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOMELAB_ROOT}/appdata/radarr:/config
      - ${HOMELAB_ROOT}/data:/data

    ports:
      - "7878:7878"

    networks:
      - media
      - monitoring

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOMELAB_ROOT}/appdata/lidarr:/config
      - ${HOMELAB_ROOT}/data:/data

    ports:
      - "8686:8686"

    networks:
      - media
      - monitoring

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
  
    depends_on:
      - sonarr
      - radarr
  
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  
    volumes:
      - ${HOMELAB_ROOT}/appdata/bazarr:/config
      - ${HOMELAB_ROOT}/data:/data
  
    ports:
      - "6767:6767"
  
    networks:
      - media
      - monitoring
      
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${HOMELAB_ROOT}/appdata/jellyfin:/config
      - ${HOMELAB_ROOT}/data/media/movies:/movies:ro
      - ${HOMELAB_ROOT}/data/media/tv:/tv:ro
      - ${HOMELAB_ROOT}/data/media/music:/music:ro
      - ${HOMELAB_ROOT}/data/media/books:/books:ro

    ports:
      - "8096:8096"

    networks:
      - media
      - monitoring

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    restart: unless-stopped

    environment:
      - TZ=${TZ}

    ports:
      - "5055:5055"

    volumes:
      - seerr-config:/app/config

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

    networks:
      - media
      - monitoring

volumes:

  sabnzbd-config:
  seerr-config:


networks:

  media:
    name: homelab-media-network

  vpn:
    name: homelab-vpn-network

  monitoring:
    external: true
    name: monitoring