name: homelab-media


services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun
    
    ports:
      - 8080:8080
      - 8081:8081

    environment:
      TZ: ${TZ}
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: ${VPN_TYPE}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}

    volumes:
      - ${HOMELAB_ROOT}/appdata/gluetun:/gluetun

    networks:
      - vpn


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    network_mode: "service:gluetun"

    depends_on:
      - gluetun

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080

    volumes:
      - ${HOMELAB_ROOT}/appdata/qbittorrent:/config
      - ${HOMELAB_ROOT}/downloads/qbittorrent:/downloads

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped

    network_mode: "service:gluetun"
    
    depends_on:
      - gluetun
      
    #ports:
    #  - "8081:8080"
    #networks:
    #  - media

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - sabnzbd-config:/config
      - ${HOMELAB_ROOT}/downloads:/downloads


volumes:

  sabnzbd-config:


networks:

  media:
    name: homelab-media-network

  vpn:
    name: homelab-vpn-network