name: homelab-infrastructure

services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}      
    ports:
      - "3000:3000"
    volumes:
      - ${HOMELAB_ROOT}/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ${HOMELAB_ROOT}/appdata/uptime-kuma:/app/data
    networks:
      - frontend
      - monitoring


networks:

  frontend:
    external: true

  monitoring:
    external: true
    name: monitoring